services:
  # --- ZOOKEEPER ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: atlantic-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - atlantic-network

  # --- KAFKA ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: atlantic-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - atlantic-network

  # --- MINIO (Data Lake Storage) ---
  minio:
    image: minio/minio:latest
    container_name: atlantic-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=atlantic_admin
      - MINIO_ROOT_PASSWORD=atlantic_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - atlantic-network

  # --- SPARK MASTER ---
  spark-master:
    image: apache/spark:3.5.3-python3
    container_name: atlantic-spark-master
    user: root
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./src/spark-jobs:/opt/spark/jobs
    networks:
      - atlantic-network

  # --- SPARK WORKER ---
  spark-worker:
    image: apache/spark:3.5.3-python3
    container_name: atlantic-spark-worker
    user: root
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./src/spark-jobs:/opt/spark/jobs
    depends_on:
      - spark-master
    networks:
      - atlantic-network

networks:
  atlantic-network:
    driver: bridge

volumes:
  minio_data: